nosyn : nosynch.c
	gcc -pthread -o nosynch nosynch.c
1: 1.c
	gcc -pthread -o 1 1.c
0: 0.c
	gcc -pthread -o 0 0.c
2: 2.c
	gcc -pthread -o 2 2.c
41: 41.c
	gcc -pthread -o cond_usg 41.c
ex3: ex3.c
	gcc -pthread -o ex3 ex3.c
